version: "2.1"
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka-broker:
    image: wurstmeister/kafka:2.12-2.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "orders:1:1,reports:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  master:
    build:
      context: .
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      - ROLE=master
      - MASTER_HOST=master
    volumes:
      - ./checkpoint-dir:/checkpoint-dir
  worker:
    build:
      context: .
    expose:
      - "6121"
      - "6122"
    depends_on:
      - master
      - kafka-broker
    links:
      - "master:master"
      - "kafka-broker:kafka-broker"
    environment:
      - ROLE=worker
      - MASTER_HOST=master
    volumes:
      - ./checkpoint-dir:/checkpoint-dir
  python-worker:
    build:
      context: ./monitoring
    expose:
      - "8000"
  order-generator:
    build:
      context: generator
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker
  results-consumer:
    build:
      context: consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker
      - database
    links:
      - database:database
  app:
    build:
      context: dashboard
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    depends_on:
      - database
    links:
      - database:database
  database:
    image: mysql
    volumes:
      - ./var/lib/mysql
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=lieferbot
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    expose:
      - 3306
