version: "2.1"
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - "2181:2181"

  kafka-broker:
    container_name: kafka-broker
    image: wurstmeister/kafka:2.12-2.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "orders:1:1,reports:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  master:
    container_name: master
    build:
      context: .
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      - ROLE=master
      - MASTER_HOST=master
    volumes:
      - ./checkpoint-dir:/checkpoint-dir

  worker:
    container_name: worker
    build:
      context: .
    expose:
      - "6121"
      - "6122"
    depends_on:
      - master
      - kafka-broker
    links:
      - "master:master"
      - "kafka-broker:kafka-broker"
    environment:
      - ROLE=worker
      - MASTER_HOST=master
    volumes:
      - ./checkpoint-dir:/checkpoint-dir

  python-worker:
    container_name: python-worker
    build:
      context: ./monitoring
    expose:
      - "8000"

  order-generator:
    container_name: order-generator
    build:
      context: generator
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker

  results-consumer:
    container_name: results-consumer
    build:
      context: consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka-broker
      - database

  app:
    container_name: app
    build:
      context: dashboard
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: lieferbot
    #    volumes:
    #      - "./db_volume:/var/lib/postgresql"
