# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='lieferbot',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\x12\tlieferbot\"H\n\x0bOrderUpdate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07vehicle\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\x02\"\x1c\n\nOrderState\x12\x0e\n\x06status\x18\x01 \x01(\t\":\n\x16OrderStateWithPrevious\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08previous\x18\x02 \x01(\x08\"\x14\n\x04Time\x12\x0c\n\x04time\x18\x01 \x01(\x02\"\x1a\n\x07NoState\x12\x0f\n\x07\x63ounter\x18\x01 \x01(\x03\"\x82\x01\n\x06Report\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07vehicle\x18\x02 \x01(\t\x12\x16\n\x0etimeUnassigned\x18\x03 \x01(\x02\x12\x14\n\x0ctimeAssigned\x18\x04 \x01(\x02\x12\x16\n\x0etimeInProgress\x18\x05 \x01(\x02\x12\x15\n\rtimeDelivered\x18\x06 \x01(\x02\"_\n\x08Overview\x12\x14\n\x0cnoUnassigned\x18\x01 \x01(\x03\x12\x12\n\nnoAssigned\x18\x02 \x01(\x03\x12\x14\n\x0cnoInProgress\x18\x03 \x01(\x03\x12\x13\n\x0bnoDelivered\x18\x04 \x01(\x03\"F\n\rTimeoutReport\x12$\n\x05order\x18\x01 \x01(\x0b\x32\x15.lieferbot.OrderState\x12\x0f\n\x07orderId\x18\x02 \x01(\tb\x06proto3'
)




_ORDERUPDATE = _descriptor.Descriptor(
  name='OrderUpdate',
  full_name='lieferbot.OrderUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lieferbot.OrderUpdate.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle', full_name='lieferbot.OrderUpdate.vehicle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='lieferbot.OrderUpdate.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='lieferbot.OrderUpdate.time', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=101,
)


_ORDERSTATE = _descriptor.Descriptor(
  name='OrderState',
  full_name='lieferbot.OrderState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='lieferbot.OrderState.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=131,
)


_ORDERSTATEWITHPREVIOUS = _descriptor.Descriptor(
  name='OrderStateWithPrevious',
  full_name='lieferbot.OrderStateWithPrevious',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='lieferbot.OrderStateWithPrevious.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='previous', full_name='lieferbot.OrderStateWithPrevious.previous', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=191,
)


_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='lieferbot.Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='lieferbot.Time.time', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=213,
)


_NOSTATE = _descriptor.Descriptor(
  name='NoState',
  full_name='lieferbot.NoState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='counter', full_name='lieferbot.NoState.counter', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=241,
)


_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='lieferbot.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='lieferbot.Report.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vehicle', full_name='lieferbot.Report.vehicle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeUnassigned', full_name='lieferbot.Report.timeUnassigned', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeAssigned', full_name='lieferbot.Report.timeAssigned', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeInProgress', full_name='lieferbot.Report.timeInProgress', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timeDelivered', full_name='lieferbot.Report.timeDelivered', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=374,
)


_OVERVIEW = _descriptor.Descriptor(
  name='Overview',
  full_name='lieferbot.Overview',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='noUnassigned', full_name='lieferbot.Overview.noUnassigned', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='noAssigned', full_name='lieferbot.Overview.noAssigned', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='noInProgress', full_name='lieferbot.Overview.noInProgress', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='noDelivered', full_name='lieferbot.Overview.noDelivered', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=471,
)


_TIMEOUTREPORT = _descriptor.Descriptor(
  name='TimeoutReport',
  full_name='lieferbot.TimeoutReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order', full_name='lieferbot.TimeoutReport.order', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderId', full_name='lieferbot.TimeoutReport.orderId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=543,
)

_TIMEOUTREPORT.fields_by_name['order'].message_type = _ORDERSTATE
DESCRIPTOR.message_types_by_name['OrderUpdate'] = _ORDERUPDATE
DESCRIPTOR.message_types_by_name['OrderState'] = _ORDERSTATE
DESCRIPTOR.message_types_by_name['OrderStateWithPrevious'] = _ORDERSTATEWITHPREVIOUS
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['NoState'] = _NOSTATE
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.message_types_by_name['Overview'] = _OVERVIEW
DESCRIPTOR.message_types_by_name['TimeoutReport'] = _TIMEOUTREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderUpdate = _reflection.GeneratedProtocolMessageType('OrderUpdate', (_message.Message,), {
  'DESCRIPTOR' : _ORDERUPDATE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:lieferbot.OrderUpdate)
  })
_sym_db.RegisterMessage(OrderUpdate)

OrderState = _reflection.GeneratedProtocolMessageType('OrderState', (_message.Message,), {
  'DESCRIPTOR' : _ORDERSTATE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:lieferbot.OrderState)
  })
_sym_db.RegisterMessage(OrderState)

OrderStateWithPrevious = _reflection.GeneratedProtocolMessageType('OrderStateWithPrevious', (_message.Message,), {
  'DESCRIPTOR' : _ORDERSTATEWITHPREVIOUS,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:lieferbot.OrderStateWithPrevious)
  })
_sym_db.RegisterMessage(OrderStateWithPrevious)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:lieferbot.Time)
  })
_sym_db.RegisterMessage(Time)

NoState = _reflection.GeneratedProtocolMessageType('NoState', (_message.Message,), {
  'DESCRIPTOR' : _NOSTATE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:lieferbot.NoState)
  })
_sym_db.RegisterMessage(NoState)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), {
  'DESCRIPTOR' : _REPORT,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:lieferbot.Report)
  })
_sym_db.RegisterMessage(Report)

Overview = _reflection.GeneratedProtocolMessageType('Overview', (_message.Message,), {
  'DESCRIPTOR' : _OVERVIEW,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:lieferbot.Overview)
  })
_sym_db.RegisterMessage(Overview)

TimeoutReport = _reflection.GeneratedProtocolMessageType('TimeoutReport', (_message.Message,), {
  'DESCRIPTOR' : _TIMEOUTREPORT,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:lieferbot.TimeoutReport)
  })
_sym_db.RegisterMessage(TimeoutReport)


# @@protoc_insertion_point(module_scope)
